#include "shader.h"
#include "parallel_hashmap/phmap.h"

#include <string>

using namespace std;
using phmap::flat_hash_map;

namespace shader {

	enum PropertyId {
		_Global_FogColor = 0,
		_Global_FogMinDistance = 1,
		_Global_FogLength = 2,
		_Global_MaxDensity = 3,
		_Global_MaxHeight = 4,
		_Global_FogWorld_Origin = 5,
		_GlobalTimeScale = 6,
		_Global_LightmapColor = 7,
		_Global_LightmapShadowColor = 8,
		_Global_LightmapDensityAddColor = 9,
		_Global_LightmapModulateColor = 10,
		_GlobalDirtColor = 11,
		_GlobalDirtRimSpecularColor = 12,
		_GlobalDirtToonColor = 13,
		_ProjectionViewProj = 14,
		_CharaColor = 15,
		_ToonDarkColor = 16,
		_ToonBrightColor = 17,
		_VertexColorToonPower = 18,
		_RimColor = 19,
		_RimStep = 20,
		_RimFeather = 21,
		_RimSpecRate = 22,
		_RimShadow = 23,
		_RimShadowRate = 24,
		_RimShadowRate2 = 25,
		_EmissiveColor = 26,
		_RimHorizonOffset = 27,
		_RimVerticalOffset = 28,
		_RimColor2 = 29,
		_RimStep2 = 30,
		_RimFeather2 = 31,
		_RimSpecRate2 = 32,
		_RimHorizonOffset2 = 33,
		_RimVerticalOffset2 = 34,
		_LightProbeColor = 35,
		_MainTex = 36,
		_MainTex_ST = 37,
		_TripleMaskMap = 38,
		_OptionMaskMap = 39,
		_UseOptionMaskMap = 40,
		_SpecularPower = 41,
		_ToonMap = 42,
		_ToonColor = 43,
		_ToonStep = 44,
		_ToonFeather = 45,
		_OutlineWidth = 46,
		_OutlineColor = 47,
		_EmissiveTex = 48,
		_ZekkenNumberTex = 49,
		_ZekkenNameTex = 50,
		_ZekkenFontColor = 51,
		_DirtTex = 52,
		_DirtRate = 53,
		_DitherTex = 54,
		_UVEmissiveScroll = 55,
		_UVEmissivePower = 56,
		_EyePupliScale = 57,
		_ClipColor = 58,
		_CheekRate = 59,
		_AppTime = 60,
		_BlurStrength = 61,
		_BlurWidth = 62,
		_CenterX = 63,
		_CenterY = 64,
		_ProjectionShadowMap = 65,
		_CompTex = 66,
		_Color = 67,
		_AddColor = 68,
		_FrontOffset = 69,
		_BackOffset = 70,
		_Offset = 71,
		_StencilMask = 72,
		_StencilComp = 73,
		_StencilOp = 74,
		_Stencil = 75,
		_Cull = 76,
		_DistortionScrollU = 77,
		_DistortionScrollV = 78,
		_AlphaParam = 79,
		_ShadowColor = 80,
		_EnableScrollAppTime = 81,
		_ReflectionRate = 82,
		_ReflectionTex = 83,
		_ReflectionMask = 84,
		_ReflectionOffsetScaleUV = 85,
		_Speed = 86,
		_Distortion = 87,
		_UCross = 88,
		_VCross = 89,
		_U = 90,
		_V = 91,
		_NormalPower = 92,
		_WaveDistortionPower = 93,
		_WaveClearly = 94,
		_WaveDiffusion = 95,
		_WaveDecline = 96,
		_IsWorldWave = 97,
		_WaveDir = 98,
		_WaveFreq = 99,
		_WaveSpeed = 100,
		_WaveSize = 101,
		_PaintUV = 102,
		_Brush = 103,
		_BrushScale = 104,
		_ControlColor = 105,
		_InputTex = 106,
		_PrevTex = 107,
		_Prev2Tex = 108,
		_FootTex = 109,
		_VOffset = 110,
		_ColorFade = 111,
		_ColorArray = 112,
		_HighParam1 = 113,
		_HighParam2 = 114,
		_MainParam = 115,
		_TexScrollParam = 116,
		_FixProjection = 117,
		_CameraLength = 118,
		_BgClipTexture = 119,
		_BgClipUVOffset = 120,
		_BgClipUVScale = 121,
		_BgClipRGBThreshold = 122,
		_UseOriginalDirectionalLight = 123,
		_OriginalDirectionalLightDir = 124,
		_FaceCenterPos = 125,
		_FaceUp = 126,
		_FaceForward = 127,
		_CheekPretenseThreshold = 128,
		_NosePretenseThreshold = 129,
		_NoseVisibility = 130,
		_CylinderBlend = 131,
		_HairNormalBlend = 132,
		_MulColor0 = 133,
		_MulColor1 = 134,
		_MulColor2 = 135,
		_ColorPower = 136,
		_ColorClampPower = 137,
		_AmbientColor = 138,
		_BrightColor = 139,
		_BaseColor = 140,
		_BorderLightDir = 141,
		_LocalTimer = 142,
		_RandomValue = 143,
		_BlurRadius4 = 144,
		_SunPosition = 145,
		_Power = 146,
		_SunColor = 147,
		_ColorBuffer = 148,
		_CenterMultiplex = 149,
		_CenterBrightness = 150,
		_BlackLevel = 151,
		_KomorebiRate = 152,
		_BlurSize = 153,
		_BlurArea = 154,
		_Params = 155,
		_Blurred = 156,
		_RgbTex = 157,
		_ZCurve = 158,
		_RgbDepthTex = 159,
		_Saturation = 160,
		selColor = 161,
		targetColor = 162,
		offsets = 163,
		_bloomDofWeight = 164,
		_CurveParams = 165,
		_InvRenderTargetSize = 166,
		_TapLowBackground = 167,
		_Bloom = 168,
		_Parameter = 169,
		_PixelSize = 170,
		_ColorParam = 171,
		_DepthPower = 172,
		_DepthPowerFront = 173,
		_DepthPowerBack = 174,
		_DepthCancelRect = 175,
		_DepthCancelBlendLength = 176,
		_PostFilmPower = 177,
		_PostFilmOffsetParam = 178,
		_PostFilmOptionParam = 179,
		_PostFilmColor0 = 180,
		_PostFilmColor1 = 181,
		_PostFilmColor2 = 182,
		_PostFilmColor3 = 183,
		_TapHigh = 184,
		_TapLowForeground = 185,
		_ForegroundBlurExtrude = 186,
		_TapMedium = 187,
		_TapLow = 188,
		_dofForegroundSize = 189,
		_texMovie = 190,
		_texMovieMask = 191,
		_movieScale = 192,
		_movieOffset = 193,
		_colorBlendFactor = 194,
		_BloomHighRange = 195,
		_bloomHighRangeIntensity = 196,
		_BlurParam = 197,
		_BlurParamEx = 198,
		_BlurTex = 199,
		_BlurStartArea = 200,
		_BlurEndArea = 201,
		_BlurPower = 202,
		_Gain = 203,
		_CameraDepthTexture = 204,
		_PostFilmRollParameter = 205,
		_PostFilmScaleParameter = 206,
		_PostFilmIsUVMovieNoScale = 207,
		_PostFilmIsInverseVignette = 208,
		_PostFilmIsAlphaMasking = 209,
		_BloomIsScreenBlend = 210,
		_PostFilmIsWithoutDepth = 211,
		_SecondTex = 212,
		_ThirdTex = 213,
		_FourthTex = 214,
		_FifthTex = 215,
		_Angle = 216,
		_Scale = 217,
		_Alpha = 218,
		_Alpha2 = 219,
		_MaskAlpha = 220,
		_ShaftsTex1 = 221,
		_ShaftsTex2 = 222,
		_ShaftsTex3 = 223,
		_ShaftsTex4 = 224,
		_ShaftsTex5 = 225,
		_MaskTex = 226,
		_FrustumCornersWS = 227,
		_CameraWS = 228,
		_HeightParams = 229,
		_DistanceParams = 230,
		_FogColor = 231,
		_SceneFogParams = 232,
		_SceneFogMode = 233,
		_Height = 234,
		_faceShadowColor = 235,
		_faceShadowAlpha = 236,
		_faceShadowEndY = 237,
		_faceShadowLength = 238,
		_faceShadowHeadMat = 239,
		_blendRate = 240,
		_blendScale = 241,
		_UVScrollX = 242,
		_UVScrollY = 243,
		_UVScrollOffsetX = 244,
		_UVScrollOffsetY = 245,
		_LensDistortion_CenterScale = 246,
		_LensDistortion_Amount = 247,
		_DepthClip = 248,
		_DistortionArea = 249,
		_HightLightParam = 250,
		_HightLightColor = 251,
		_OffsetColorX = 252,
		_OffsetColorY = 253,
		_Lut2D_Params = 254,
		_Lut2D = 255,
		_MaxCoC = 256,
		_Aspect = 257,
		_DrawRect = 258,
		_EdgeWidth = 259,
		_lowResFixScaleX = 260,
		_lowResFixScaleY = 261,
		_lowResOffsetX = 262,
		_lowResOffsetY = 263,
		_FlipMaskAlpha = 264,
		_FadeValue = 265,
		_LineThickness = 266,
		_MaskPosArray = 267,
		_GroupMatrices = 268,
		_ShadowFadeCenter = 269,
		_ShadowFadeFront = 270,
		_ShadowFadeParam = 271,
		_ShadowStartColor = 272,
		_ShadowEndColor = 273,
		_IsBinarization = 274,
		_DirShadowColor = 275,
		_DirShadowIntensity = 276,
		_ProjectorMulColor0 = 277,
		_ProjectorColorPower = 278,
		_MaskColorTex = 279,
		_MaskColorR1 = 280,
		_MaskColorR2 = 281,
		_MaskColorG1 = 282,
		_MaskColorG2 = 283,
		_MaskColorB1 = 284,
		_MaskColorB2 = 285,
		_MaskToonColorR1 = 286,
		_MaskToonColorR2 = 287,
		_MaskToonColorG1 = 288,
		_MaskToonColorG2 = 289,
		_MaskToonColorB1 = 290,
		_MaskToonColorB2 = 291,
		_BlendFactor = 292,
		_UVAdjust = 293,
		_MonitorWidth = 294,
		_MonitorHeight = 295,
		_Cutoff = 296,
		_High0Tex = 297,
		_High1Tex = 298,
		_High2Tex = 299,
		_Timer = 300,
		_VertexLerpColor = 301,
		_ColorLerpRate = 302,
		_FlickerLightRate = 303,
		_FlickerDarkRate = 304,
		_CullMode = 305,
		_ZTestMode = 306,
		_ScrollX = 307,
		_ScrollOffsetX = 308,
		_TimeOffset = 309,
		_VertexScale = 310,
		_ZBufferParams = 311,
		_AlphaArray = 312,
		_SplitScreenVerticalNum = 313,
		_SplitScreenHorizontalNum = 314,
		_UVOffset = 315,
		_Transform = 316,
		_LineColor = 317,
		_LineAntialiasing = 318,
		_ScreenScale = 319,
		_WindScale = 320,
		_WindParam = 321,
		_WindDirTex = 322,
		_FadeColor = 323,
		_FadeRate = 324,
		_ZWrite = 325,
		_ZTest = 326,
		_CurveTex = 327,
		_MinLevel = 328,
		_MaxLevel = 329,
		_MaskMinLevel = 330,
		_MaskMaxLevel = 331,
		_DepthMask = 332,
		_NoiseTex = 333,
		_NoiseTex_ST = 334,
		_ShellAmountMax = 335,
		_ShellAmount = 336,
		_ShellStep = 337,
		_ShellStepScale = 338,
		_AlphaCutout = 339,
		_Occlusion = 340,
		_BaseMove = 341,
		_WindFreq = 342,
		_WindMove = 343,
		_Brightness = 344,
		_GrassFadeBeginDist = 345,
		_GrassFadeEndDist = 346,
		_GrassFadeOffsetPower = 347,
		_SubTex = 348,
		_LightTex = 349,
		_MultimapRate = 350,
		_Fresnel = 351,
		_ViewDir = 352,
		_AxisFramesX = 353,
		_AxisFramesY = 354,
		_UpperAngle = 355,
		_LowerAngle = 356,
		_LightmapColorRate = 357,
		_Temp = 358,
		_UScrollSurpport = 359,
		_VScrollSurpport = 360,
		_TrailCustom1_b = 361,
		_TrailCustom1_a = 362,
		_TrailCustom2_r = 363,
		_TrailCustom2_g = 364,
		_TrailCustom2_b = 365,
		_TrailCustom2_a = 366,
		_ScreenColorPower = 367,
		_EffectColorPower = 368,
		_SrcBlend = 369,
		_DstBlend = 370
	};

	
	flat_hash_map<string, string> ShaderTypeDic =
	{
		{"_Global_FogColor", "Color"},
		{"_Global_FogMinDistance", ""},
		{"_Global_FogLength", ""},
		{"_Global_MaxDensity", ""},
		{"_Global_MaxHeight", ""},
		{"_Global_FogWorld_Origin", ""},
		{"_GlobalTimeScale", ""},
		{"_Global_LightmapColor", ""},
		{"_Global_LightmapShadowColor", ""},
		{"_Global_LightmapDensityAddColor", ""},
		{"_Global_LightmapModulateColor", ""},
		{"_GlobalDirtColor", ""},
		{"_GlobalDirtRimSpecularColor", ""},
		{"_GlobalDirtToonColor", ""},
		{"_ProjectionViewProj", ""},
		{"_CharaColor", "Color"},
		{"_ToonDarkColor", "Color"},
		{"_ToonBrightColor", "Color"},
		{"_VertexColorToonPower", "Float"},
		{"_RimColor", "Color"},
		{"_RimStep", "Float"},
		{"_RimFeather", "Float"},
		{"_RimSpecRate", "Float"},
		{"_RimShadow", "Float"},
		{"_RimShadowRate", "Float"},
		{"_RimShadowRate2", "Float"},
		{"_EmissiveColor", "Color"},
		{"_RimHorizonOffset", "Float"},
		{"_RimVerticalOffset", "Float"},
		{"_RimColor2", "Color"},
		{"_RimStep2", "Float"},
		{"_RimFeather2", "Float"},
		{"_RimSpecRate2", "Float"},
		{"_RimHorizonOffset2", "Float"},
		{"_RimVerticalOffset2", "Float"},
		{"_LightProbeColor", "Color"},
		{"_MainTex", "2D"},
		{"_MainTex_ST", "Vector"},
		{"_TripleMaskMap", "2D"},
		{"_OptionMaskMap", "2D"},
		{"_UseOptionMaskMap", "Float"},
		{"_SpecularPower", "Float"},
		{"_ToonMap", "2D"},
		{"_ToonColor", "Color"},
		{"_ToonStep", "Float"},
		{"_ToonFeather", "Float"},
		{"_OutlineWidth", "Float"},
		{"_OutlineColor", "Color"},
		{"_EmissiveTex", "2D"},
		{"_ZekkenNumberTex", ""},
		{"_ZekkenNameTex", ""},
		{"_ZekkenFontColor", ""},
		{"_DirtTex", "2D"},
		{"_DirtRate", ""},
		{"_DitherTex", ""},
		{"_UVEmissiveScroll", ""},
		{"_UVEmissivePower", ""},
		{"_EyePupliScale", ""},
		{"_ClipColor", ""},
		{"_CheekRate", "Float"},
		{"_AppTime", ""},
		{"_BlurStrength", ""},
		{"_BlurWidth", ""},
		{"_CenterX", ""},
		{"_CenterY", ""},
		{"_ProjectionShadowMap", ""},
		{"_CompTex", ""},
		{"_Color", ""},
		{"_AddColor", ""},
		{"_FrontOffset", ""},
		{"_BackOffset", ""},
		{"_Offset", ""},
		{"_StencilMask", "Float"},
		{"_StencilComp", "Float"},
		{"_StencilOp", "Float"},
		{"_Stencil", ""},
		{"_Cull", ""},
		{"_DistortionScrollU", ""},
		{"_DistortionScrollV", ""},
		{"_AlphaParam", ""},
		{"_ShadowColor", "Color"},
		{"_EnableScrollAppTime", ""},
		{"_ReflectionRate", ""},
		{"_ReflectionTex", ""},
		{"_ReflectionMask", ""},
		{"_ReflectionOffsetScaleUV", ""},
		{"_Speed", ""},
		{"_Distortion", ""},
		{"_UCross", ""},
		{"_VCross", ""},
		{"_U", ""},
		{"_V", ""},
		{"_NormalPower", ""},
		{"_WaveDistortionPower", ""},
		{"_WaveClearly", ""},
		{"_WaveDiffusion", ""},
		{"_WaveDecline", ""},
		{"_IsWorldWave", ""},
		{"_WaveDir", ""},
		{"_WaveFreq", ""},
		{"_WaveSpeed", ""},
		{"_WaveSize", ""},
		{"_PaintUV", ""},
		{"_Brush", ""},
		{"_BrushScale", ""},
		{"_ControlColor", ""},
		{"_InputTex", ""},
		{"_PrevTex", ""},
		{"_Prev2Tex", ""},
		{"_FootTex", ""},
		{"_VOffset", ""},
		{"_ColorFade", ""},
		{"_ColorArray", ""},
		{"_HighParam1", ""},
		{"_HighParam2", ""},
		{"_MainParam", ""},
		{"_TexScrollParam", ""},
		{"_FixProjection", ""},
		{"_CameraLength", ""},
		{"_BgClipTexture", ""},
		{"_BgClipUVOffset", ""},
		{"_BgClipUVScale", ""},
		{"_BgClipRGBThreshold", ""},
		{"_UseOriginalDirectionalLight", "Float"},
		{"_OriginalDirectionalLightDir", "Vector"},
		{"_FaceCenterPos", "Vector"},
		{"_FaceUp", "Vector"},
		{"_FaceForward", "Vector"},
		{"_CheekPretenseThreshold", "Float"},
		{"_NosePretenseThreshold", "Float"},
		{"_NoseVisibility", "Float"},
		{"_CylinderBlend", "Float"},
		{"_HairNormalBlend", "Float"},
		{"_MulColor0", ""},
		{"_MulColor1", ""},
		{"_MulColor2", ""},
		{"_ColorPower", ""},
		{"_ColorClampPower", ""},
		{"_AmbientColor", ""},
		{"_BrightColor", ""},
		{"_BaseColor", ""},
		{"_BorderLightDir", ""},
		{"_LocalTimer", ""},
		{"_RandomValue", ""},
		{"_BlurRadius4", ""},
		{"_SunPosition", ""},
		{"_Power", ""},
		{"_SunColor", ""},
		{"_ColorBuffer", ""},
		{"_CenterMultiplex", ""},
		{"_CenterBrightness", ""},
		{"_BlackLevel", ""},
		{"_KomorebiRate", ""},
		{"_BlurSize", ""},
		{"_BlurArea", ""},
		{"_Params", ""},
		{"_Blurred", ""},
		{"_RgbTex", ""},
		{"_ZCurve", ""},
		{"_RgbDepthTex", ""},
		{"_Saturation", "Float"},
		{"selColor", ""},
		{"targetColor", ""},
		{"offsets", ""},
		{"_bloomDofWeight", ""},
		{"_CurveParams", ""},
		{"_InvRenderTargetSize", ""},
		{"_TapLowBackground", ""},
		{"_Bloom", ""},
		{"_Parameter", ""},
		{"_PixelSize", ""},
		{"_ColorParam", ""},
		{"_DepthPower", ""},
		{"_DepthPowerFront", ""},
		{"_DepthPowerBack", ""},
		{"_DepthCancelRect", ""},
		{"_DepthCancelBlendLength", ""},
		{"_PostFilmPower", ""},
		{"_PostFilmOffsetParam", ""},
		{"_PostFilmOptionParam", ""},
		{"_PostFilmColor0", ""},
		{"_PostFilmColor1", ""},
		{"_PostFilmColor2", ""},
		{"_PostFilmColor3", ""},
		{"_TapHigh", ""},
		{"_TapLowForeground", ""},
		{"_ForegroundBlurExtrude", ""},
		{"_TapMedium", ""},
		{"_TapLow", ""},
		{"_dofForegroundSize", ""},
		{"_texMovie", ""},
		{"_texMovieMask", ""},
		{"_movieScale", ""},
		{"_movieOffset", ""},
		{"_colorBlendFactor", ""},
		{"_BloomHighRange", ""},
		{"_bloomHighRangeIntensity", ""},
		{"_BlurParam", ""},
		{"_BlurParamEx", ""},
		{"_BlurTex", ""},
		{"_BlurStartArea", ""},
		{"_BlurEndArea", ""},
		{"_BlurPower", ""},
		{"_Gain", ""},
		{"_CameraDepthTexture", ""},
		{"_PostFilmRollParameter", ""},
		{"_PostFilmScaleParameter", ""},
		{"_PostFilmIsUVMovieNoScale", ""},
		{"_PostFilmIsInverseVignette", ""},
		{"_PostFilmIsAlphaMasking", ""},
		{"_BloomIsScreenBlend", ""},
		{"_PostFilmIsWithoutDepth", ""},
		{"_SecondTex", ""},
		{"_ThirdTex", ""},
		{"_FourthTex", ""},
		{"_FifthTex", ""},
		{"_Angle", ""},
		{"_Scale", ""},
		{"_Alpha", ""},
		{"_Alpha2", ""},
		{"_MaskAlpha", ""},
		{"_ShaftsTex1", ""},
		{"_ShaftsTex2", ""},
		{"_ShaftsTex3", ""},
		{"_ShaftsTex4", ""},
		{"_ShaftsTex5", ""},
		{"_MaskTex", ""},
		{"_FrustumCornersWS", ""},
		{"_CameraWS", ""},
		{"_HeightParams", ""},
		{"_DistanceParams", ""},
		{"_FogColor", ""},
		{"_SceneFogParams", ""},
		{"_SceneFogMode", ""},
		{"_Height", ""},
		{"_faceShadowColor", "Color"},
		{"_faceShadowAlpha", "Float"},
		{"_faceShadowEndY", "Float"},
		{"_faceShadowLength", "Float"},
		{"_faceShadowHeadMat", ""},
		{"_blendRate", ""},
		{"_blendScale", ""},
		{"_UVScrollX", ""},
		{"_UVScrollY", ""},
		{"_UVScrollOffsetX", ""},
		{"_UVScrollOffsetY", ""},
		{"_LensDistortion_CenterScale", ""},
		{"_LensDistortion_Amount", ""},
		{"_DepthClip", ""},
		{"_DistortionArea", ""},
		{"_HightLightParam", ""},
		{"_HightLightColor", ""},
		{"_OffsetColorX", ""},
		{"_OffsetColorY", ""},
		{"_Lut2D_Params", ""},
		{"_Lut2D", ""},
		{"_MaxCoC", ""},
		{"_Aspect", ""},
		{"_DrawRect", ""},
		{"_EdgeWidth", ""},
		{"_lowResFixScaleX", ""},
		{"_lowResFixScaleY", ""},
		{"_lowResOffsetX", ""},
		{"_lowResOffsetY", ""},
		{"_FlipMaskAlpha", ""},
		{"_FadeValue", ""},
		{"_LineThickness", ""},
		{"_MaskPosArray", ""},
		{"_GroupMatrices", ""},
		{"_ShadowFadeCenter", ""},
		{"_ShadowFadeFront", ""},
		{"_ShadowFadeParam", ""},
		{"_ShadowStartColor", ""},
		{"_ShadowEndColor", ""},
		{"_IsBinarization", ""},
		{"_DirShadowColor", ""},
		{"_DirShadowIntensity", ""},
		{"_ProjectorMulColor0", ""},
		{"_ProjectorColorPower", ""},
		{"_MaskColorTex", "2D"},
		{"_MaskColorR1", "Color"},
		{"_MaskColorR2", "Color"},
		{"_MaskColorG1", "Color"},
		{"_MaskColorG2", "Color"},
		{"_MaskColorB1", "Color"},
		{"_MaskColorB2", "Color"},
		{"_MaskToonColorR1", "Color"},
		{"_MaskToonColorR2", "Color"},
		{"_MaskToonColorG1", "Color"},
		{"_MaskToonColorG2", "Color"},
		{"_MaskToonColorB1", "Color"},
		{"_MaskToonColorB2", "Color"},
		{"_BlendFactor", ""},
		{"_UVAdjust", ""},
		{"_MonitorWidth", ""},
		{"_MonitorHeight", ""},
		{"_Cutoff", "Float"},
		{"_High0Tex", ""},
		{"_High1Tex", ""},
		{"_High2Tex", ""},
		{"_Timer", ""},
		{"_VertexLerpColor", ""},
		{"_ColorLerpRate", ""},
		{"_FlickerLightRate", ""},
		{"_FlickerDarkRate", ""},
		{"_CullMode", ""},
		{"_ZTestMode", ""},
		{"_ScrollX", ""},
		{"_ScrollOffsetX", ""},
		{"_TimeOffset", ""},
		{"_VertexScale", ""},
		{"_ZBufferParams", ""},
		{"_AlphaArray", ""},
		{"_SplitScreenVerticalNum", ""},
		{"_SplitScreenHorizontalNum", ""},
		{"_UVOffset", ""},
		{"_Transform", ""},
		{"_LineColor", ""},
		{"_LineAntialiasing", ""},
		{"_ScreenScale", ""},
		{"_WindScale", ""},
		{"_WindParam", ""},
		{"_WindDirTex", ""},
		{"_FadeColor", ""},
		{"_FadeRate", ""},
		{"_ZWrite", ""},
		{"_ZTest", ""},
		{"_CurveTex", ""},
		{"_MinLevel", ""},
		{"_MaxLevel", ""},
		{"_MaskMinLevel", ""},
		{"_MaskMaxLevel", ""},
		{"_DepthMask", ""},
		{"_NoiseTex", ""},
		{"_NoiseTex_ST", ""},
		{"_ShellAmountMax", ""},
		{"_ShellAmount", ""},
		{"_ShellStep", ""},
		{"_ShellStepScale", ""},
		{"_AlphaCutout", ""},
		{"_Occlusion", ""},
		{"_BaseMove", ""},
		{"_WindFreq", ""},
		{"_WindMove", ""},
		{"_Brightness", ""},
		{"_GrassFadeBeginDist", ""},
		{"_GrassFadeEndDist", ""},
		{"_GrassFadeOffsetPower", ""},
		{"_SubTex", ""},
		{"_LightTex", ""},
		{"_MultimapRate", ""},
		{"_Fresnel", ""},
		{"_ViewDir", ""},
		{"_AxisFramesX", ""},
		{"_AxisFramesY", ""},
		{"_UpperAngle", ""},
		{"_LowerAngle", ""},
		{"_LightmapColorRate", ""},
		{"_Temp", ""},
		{"_UScrollSurpport", ""},
		{"_VScrollSurpport", ""},
		{"_TrailCustom1_b", ""},
		{"_TrailCustom1_a", ""},
		{"_TrailCustom2_r", ""},
		{"_TrailCustom2_g", ""},
		{"_TrailCustom2_b", ""},
		{"_TrailCustom2_a", ""},
		{"_ScreenColorPower", ""},
		{"_EffectColorPower", ""},
		{"_SrcBlend", ""},
		{"_DstBlend", ""},
		//Add
		{ "_SpecularColor", "Color" },
		{ "_EnvMap", "2D" },
		{ "_EnvRate", "Float" },
		{ "_EnvBias", "Float" },
		{ "_DirtScale", "Float" }
	};
	
}